---
- hosts: apt
  gather_facts: yes
  become: yes

  tasks:
    - name: preform a dist-upgrade.
      apt:
        upgrade: dist
        update_cache: yes

    - name: check if reboot is requierd.
      stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

    - name: Reboot the server (if required)
      reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer requierd.
      apt:
        autoremove: yes
